### ISSUE TITLE
Bug: Does not work for images stored on S3 storage

### ISSUE THREAD

**Issue by nschoenwald** [ggagnon76/scene-scroller-maker#23] opened 2022-10-16 08:19 UTC
When applying to images stored on S3 storage, the converting does not work. The module appears to attempt to save to a wrong local folder:

![Greenshot 2022-10-16 10 17 40](https://user-images.githubusercontent.com/72390280/196025728-a7f19b42-9896-4159-a8b5-22d4363ac713.png)

**Comment by ggagnon76** [comment] 2022-10-16 14:16
I am aware.  This has been reported in issue #19 .

This will be difficult for me to test as I don't have an S3 bucket.

**Comment by ggagnon76** [comment] 2022-10-24 00:14
This is hopefully resolved with release of V2.1 (sorry, I can't test this...)

**Comment by nschoenwald** [comment] 2022-10-24 16:32
I just tested with an existing scene saved on S3. I chose "same location" and got the following error (see images attached).
<img width="845" alt="Greenshot 2022-10-24 18 31 24" src="https://user-images.githubusercontent.com/72390280/197578163-8bf38d4f-c4c8-44e4-b528-e51f7cde5fb2.png">
<img width="328" alt="Greenshot 2022-10-24 18 31 49" src="https://user-images.githubusercontent.com/72390280/197578172-cce62d4b-1c75-4981-a523-1c726eb59c89.png">

**Comment by ggagnon76** [comment] 2022-10-24 16:36
Thank you for your feedback.  I will have to ask core devs to help as I can't test by doing.

**Comment by ggagnon76** [comment] 2022-10-24 16:53
Is that the whole error stack?  `foundry.js:58721` is just about spitting out the warning notification.

**Comment by ggagnon76** [comment] 2022-10-28 01:39
Tried another fix with v2.2.2.  

Need feedback to know if the issue is resolved or not.

**Comment by nschoenwald** [comment] 2022-10-28 20:00
It mostly works! Converting and saving to S3 worked in my test now, the filename was just automatically changed to a local filename (which did not exist, but the file was created in the correct location in the S3 bucket).

**Comment by ggagnon76** [comment] 2022-10-31 11:07
Can you give me an example of what the file name was, then what it became?

**Comment by nschoenwald** [comment] 2022-10-31 11:10
It was https://bucketname.eu-west-3.amazonaws.com/toa/scenes-mood/PortNyanzaru-annotated.jpg and became toa/scenes-mood/PortNyanzaru-annotated.webp, so it is missing the S3 bucket name part.

**Comment by nschoenwald** [comment] 2022-10-31 11:12
For clarity: the new file is uploaded to the correct location in the s3 bucket, this just affects the scene settings.

**Comment by ggagnon76** [comment] 2022-10-31 11:16
Ahh.  So your scene won't show the image because the path isn't pointing to the S3 bucket?
(You blacked out your S3 bucket path last times you posted.  I can see the entire path in your latest reply.)

**Comment by nschoenwald** [comment] 2022-10-31 11:17
Yeah, exactly! I have to manually add that part afterwards.

Snowmane Gaming ***@***.***> schrieb am Mo., 31. Okt. 2022,
12:16:

**Comment by ggagnon76** [comment] 2022-11-03 01:20
I created my own S3 bucket.  It wasn't configured properly (wouldn't let me upload), but it was sufficient for me to be able to debug. I strongly suspect/hope that the new release of v2.3.1 has resolved this issue.

I will leave this issue open until this release can be confirmed to be working.

**Comment by ggagnon76** [comment] 2022-11-11 00:43
Closing this for now.  If a follow up response demonstrates it doesn't work, then the issue will be reopened.

**Closed as completed by ggagnon76** 2022-11-11 00:43 UTC
Labels: bug
